# Generated by Django 5.1.2 on 2024-10-29 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'recrutador': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='base.dadosusuario'),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'recrutador': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dados_pessoais', to='base.dadosusuario'),
        ),
        migrations.AddField(
            model_name='dadosusuario',
            name='recrutador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='usuario',
            field=models.ForeignKey(blank=True, limit_choices_to={'recrutador': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_profissionais', to='base.dadosusuario'),
        ),
        migrations.AddField(
            model_name='formacaoacademica',
            name='usuario',
            field=models.ForeignKey(blank=True, limit_choices_to={'recrutador': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formacoes_academicas', to='base.dadosusuario'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contato',
            name='endereco',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dadosusuario',
            name='senha',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dadosusuario',
            name='usuario',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='cargo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='empresa',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formacaoacademica',
            name='curso',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='formacaoacademica',
            name='instituicao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='formacaoacademica',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
