# Generated by Django 5.1.2 on 2024-10-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contato_usuario_dadospessoais_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosusuario',
            name='usuario',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
