# Generated by Django 5.1.2 on 2024-10-30 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_dadosusuario_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosusuario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dados_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dadosusuario',
            name='usuario',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
